name: CI

on:
  push: ~
  pull_request: ~

jobs:
  build:
    name: Test
    runs-on: Ubuntu-20.04

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: 8.0
          coverage: none

      - name: Download dependencies
        uses: ramsey/composer-install@v1

      - name: Run tests
        run: ./bin/console cache:warmup --env dev
